---
- name: restart samba
  become: true
  service: name=smbd state=restarted

- name: add samba users
  become: yes
  shell: (echo {{ item.password }}; echo {{ item.password}})|smbpasswd -s -a samba-{{ item.name }}
  with_items:
    samba_users
  no_log: True
  notify: restart samba
